//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WZDE.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WZDE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;tr&gt;
        ///   &lt;td valign=top style=&apos;border-top:solid windowtext 1.0pt;
        ///  border-left:solid windowtext 1.0pt;border-bottom:none;border-right:none;
        ///  padding:0cm 0cm 0cm 0cm&apos;&gt;
        ///  &lt;p class=MsoNormal style=&apos;margin-bottom:0cm;margin-bottom:.0001pt;line-height:
        ///  normal;text-autospace:none&apos;&gt;&lt;span style=&apos;font-size:9.0pt;font-family:&quot;Arial Narrow&quot;,&quot;sans-serif&quot;;
        ///  color:black&apos;&gt;&amp;nbsp;&lt;/span&gt;&lt;/p&gt;
        ///  &lt;/td&gt;
        ///  &lt;td valign=top style=&apos;border-top:solid windowtext 1.0pt;
        ///  border-left:solid windowtext 1.0pt;border-bottom:non [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string Ldzialka {
            get {
                return ResourceManager.GetString("Ldzialka", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;tr&gt;
        ///   &lt;td valign=top style=&apos;border-top:solid windowtext 1.0pt;
        ///  border-left:solid windowtext 1.0pt;border-bottom:none;border-right:none;
        ///  padding:0cm 0cm 0cm 0cm&apos;&gt;
        ///  &lt;p class=MsoNormal style=&apos;margin-bottom:0cm;margin-bottom:.0001pt;line-height:
        ///  normal;text-align:center;text-autospace:none&apos;&gt;&lt;span style=&apos;font-size:9.0pt;font-family:&quot;Arial Narrow&quot;,&quot;sans-serif&quot;;
        ///  color:black&apos;&gt;&amp;lt;JrS&amp;gt;&lt;/span&gt;&lt;/p&gt;
        ///  &lt;/td&gt;
        ///  &lt;td valign=top style=&apos;border-top:solid windowtext 1.0pt;
        ///  border-left:solid windowtext  [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string LdzialkaJednRejBezKW {
            get {
                return ResourceManager.GetString("LdzialkaJednRejBezKW", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;tr&gt;
        ///   &lt;td valign=top style=&apos;border-top:solid windowtext 1.0pt;
        ///  border-left:solid windowtext 1.0pt;border-bottom:none;border-right:none;
        ///  padding:0cm 0cm 0cm 0cm&apos;&gt;
        ///  &lt;p class=MsoNormal style=&apos;margin-bottom:0cm;margin-bottom:.0001pt;line-height:
        ///  normal;text-align:center;text-autospace:none&apos;&gt;&lt;span style=&apos;font-size:9.0pt;font-family:&quot;Arial Narrow&quot;,&quot;sans-serif&quot;;
        ///  color:black&apos;&gt;&amp;lt;JrS&amp;gt;&lt;/span&gt;&lt;/p&gt;
        ///  &lt;/td&gt;
        ///  &lt;td valign=top style=&apos;border-top:solid windowtext 1.0pt;
        ///  border-left:solid windowtext  [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string LdzialkaKW {
            get {
                return ResourceManager.GetString("LdzialkaKW", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;tr&gt;
        ///  &lt;td valign=top style=&apos;border-top:solid windowtext 1.0pt;
        ///  border-left:solid windowtext 1.0pt;border-bottom:none;border-right:none;
        ///  padding:0cm 0cm 0cm 0cm&apos;&gt;
        ///  &lt;p class=MsoNormal style=&apos;margin-bottom:0cm;margin-bottom:.0001pt;line-height:
        ///  normal;text-autospace:none&apos;&gt;&lt;span style=&apos;font-size:9.0pt;font-family:&quot;Arial Narrow&quot;,&quot;sans-serif&quot;;
        ///  color:black&apos;&gt;&amp;nbsp;&lt;/span&gt;&lt;/p&gt;
        ///  &lt;/td&gt;
        ///  &lt;td valign=top style=&apos;border-top:solid windowtext 1.0pt;
        ///  border-left:solid windowtext 1.0pt;border-bottom:none [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string Lpusty {
            get {
                return ResourceManager.GetString("Lpusty", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;tr&gt;
        ///  &lt;td valign=top style=&apos;border-top:solid windowtext 1.0pt;
        ///  border-left:solid windowtext 1.0pt;border-bottom:none;border-right:none;
        ///  padding:0cm 0cm 0cm 0cm&apos;&gt;
        ///  &lt;p class=MsoNormal style=&apos;margin-bottom:0cm;margin-bottom:.0001pt;line-height:
        ///  normal;text-autospace:none&apos;&gt;&lt;span style=&apos;font-size:9.0pt;font-family:&quot;Arial Narrow&quot;,&quot;sans-serif&quot;;
        ///  color:black&apos;&gt;&amp;nbsp;&lt;/span&gt;&lt;/p&gt;
        ///  &lt;/td&gt;
        ///  &lt;td valign=top style=&apos;border-top:solid windowtext 1.0pt;
        ///  border-left:solid windowtext 1.0pt;border-bottom:none [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string LpustyJednRejBezKW {
            get {
                return ResourceManager.GetString("LpustyJednRejBezKW", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;tr&gt;
        ///  &lt;td valign=top style=&apos;border-top:solid windowtext 1.0pt;
        ///  border-left:solid windowtext 1.0pt;border-bottom:none;border-right:none;
        ///  padding:0cm 0cm 0cm 0cm&apos;&gt;
        ///  &lt;p class=MsoNormal style=&apos;margin-bottom:0cm;margin-bottom:.0001pt;line-height:
        ///  normal;text-autospace:none&apos;&gt;&lt;span style=&apos;font-size:9.0pt;font-family:&quot;Arial Narrow&quot;,&quot;sans-serif&quot;;
        ///  color:black&apos;&gt;&amp;nbsp;&lt;/span&gt;&lt;/p&gt;
        ///  &lt;/td&gt;
        ///  &lt;td valign=top style=&apos;border-top:solid windowtext 1.0pt;
        ///  border-left:solid windowtext 1.0pt;border-bottom:none [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string LpustyKW {
            get {
                return ResourceManager.GetString("LpustyKW", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu  &lt;tr&gt;
        ///  &lt;td valign=top style=&apos;border-top:solid windowtext 1.0pt;
        ///  border-left:solid windowtext 1.0pt;border-bottom:none;border-right:none;
        ///  padding:0cm 0cm 0cm 0cm&apos;&gt;
        ///  &lt;p class=MsoNormal style=&apos;margin-bottom:0cm;margin-bottom:.0001pt;line-height:
        ///  normal;text-autospace:none&apos;&gt;&lt;span style=&apos;font-size:9.0pt;font-family:&quot;Arial Narrow&quot;,&quot;sans-serif&quot;;
        ///  color:black&apos;&gt;&lt;/span&gt;&lt;/p&gt;
        ///  &lt;/td&gt;
        ///  &lt;td valign=top style=&apos;border-top:solid windowtext 1.0pt;
        ///  border-left:solid windowtext 1.0pt;border-bottom:none;bord [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string Luzytek {
            get {
                return ResourceManager.GetString("Luzytek", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu  &lt;tr&gt;
        ///  &lt;td valign=top style=&apos;border-top:solid windowtext 1.0pt;
        ///  border-left:solid windowtext 1.0pt;border-bottom:none;border-right:none;
        ///  padding:0cm 0cm 0cm 0cm&apos;&gt;
        ///  &lt;p class=MsoNormal style=&apos;margin-bottom:0cm;margin-bottom:.0001pt;line-height:
        ///  normal;text-autospace:none&apos;&gt;&lt;span style=&apos;font-size:9.0pt;font-family:&quot;Arial Narrow&quot;,&quot;sans-serif&quot;;
        ///  color:black&apos;&gt;&lt;/span&gt;&lt;/p&gt;
        ///  &lt;/td&gt;
        ///  &lt;td valign=top style=&apos;border-top:solid windowtext 1.0pt;
        ///  border-left:solid windowtext 1.0pt;border-bottom:none;bord [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string LuzytekJednRejBezKW {
            get {
                return ResourceManager.GetString("LuzytekJednRejBezKW", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu  &lt;tr&gt;
        ///  &lt;td valign=top style=&apos;border-top:solid windowtext 1.0pt;
        ///  border-left:solid windowtext 1.0pt;border-bottom:none;border-right:none;
        ///  padding:0cm 0cm 0cm 0cm&apos;&gt;
        ///  &lt;p class=MsoNormal style=&apos;margin-bottom:0cm;margin-bottom:.0001pt;line-height:
        ///  normal;text-autospace:none&apos;&gt;&lt;span style=&apos;font-size:9.0pt;font-family:&quot;Arial Narrow&quot;,&quot;sans-serif&quot;;
        ///  color:black&apos;&gt;&lt;/span&gt;&lt;/p&gt;
        ///  &lt;/td&gt;
        ///  &lt;td valign=top style=&apos;border-top:solid windowtext 1.0pt;
        ///  border-left:solid windowtext 1.0pt;border-bottom:none;bord [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string LuzytekKW {
            get {
                return ResourceManager.GetString("LuzytekKW", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 
        ///  &lt;td valign=top style=&apos;border-top:solid windowtext 1.0pt;
        ///  border-left:solid windowtext 1.0pt;border-bottom:none;border-right:none;
        ///  padding:0cm 0cm 0cm 0cm&apos;&gt;
        ///  &lt;p class=MsoNormal align=center style=&apos;margin-bottom:0cm;margin-bottom:.0001pt;
        ///  text-align:center;line-height:normal;text-autospace:none&apos;&gt;&lt;b&gt;&lt;span
        ///  style=&apos;font-size:9.0pt;font-family:&quot;Arial Narrow&quot;,&quot;sans-serif&quot;;color:black&apos;&gt;&amp;lt;nDZ&amp;gt;&lt;/span&gt;&lt;/b&gt;&lt;/p&gt;
        ///  &lt;/td&gt;
        ///  &lt;td valign=top style=&apos;border-top:solid windowtext 1.0pt;
        ///  border-left:sol [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string Pdzialka {
            get {
                return ResourceManager.GetString("Pdzialka", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 
        ///  &lt;td valign=top style=&apos;border-top:solid windowtext 1.0pt;
        ///  border-left:solid windowtext 1.0pt;border-bottom:none;border-right:none;
        ///  padding:0cm 0cm 0cm 0cm&apos;&gt;
        ///  &lt;p class=MsoNormal align=center style=&apos;margin-bottom:0cm;margin-bottom:.0001pt;
        ///  text-align:center;line-height:normal;text-autospace:none&apos;&gt;&lt;b&gt;&lt;span
        ///  style=&apos;font-size:9.0pt;font-family:&quot;Arial Narrow&quot;,&quot;sans-serif&quot;;color:black&apos;&gt;&amp;lt;nDZ&amp;gt;&lt;/span&gt;&lt;/b&gt;&lt;/p&gt;
        ///  &lt;/td&gt;
        ///  &lt;td valign=top style=&apos;border-top:solid windowtext 1.0pt;
        ///  border-left:sol [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string PdzialkaJednRejBezKW {
            get {
                return ResourceManager.GetString("PdzialkaJednRejBezKW", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 
        ///  &lt;td valign=top style=&apos;border-top:solid windowtext 1.0pt;
        ///  border-left:solid windowtext 1.0pt;border-bottom:none;border-right:none;
        ///  padding:0cm 0cm 0cm 0cm&apos;&gt;
        ///  &lt;p class=MsoNormal align=center style=&apos;margin-bottom:0cm;margin-bottom:.0001pt;
        ///  text-align:center;line-height:normal;text-autospace:none&apos;&gt;&lt;b&gt;&lt;span
        ///  style=&apos;font-size:9.0pt;font-family:&quot;Arial Narrow&quot;,&quot;sans-serif&quot;;color:black&apos;&gt;&amp;lt;nDZ&amp;gt;&lt;/span&gt;&lt;/b&gt;&lt;/p&gt;
        ///  &lt;/td&gt;
        ///  &lt;td valign=top style=&apos;border-top:solid windowtext 1.0pt;
        ///  border-left:sol [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string PdzialkaKW {
            get {
                return ResourceManager.GetString("PdzialkaKW", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;td valign=top style=&apos;border-top:solid windowtext 1.0pt;
        ///  border-left:solid windowtext 1.0pt;border-bottom:none;border-right:none;
        ///  padding:0cm 0cm 0cm 0cm&apos;&gt;
        ///  &lt;p class=MsoNormal align=center style=&apos;margin-bottom:0cm;margin-bottom:.0001pt;
        ///  text-align:center;line-height:normal;text-autospace:none&apos;&gt;&lt;b&gt;&lt;span
        ///  style=&apos;font-size:9.0pt;font-family:&quot;Arial Narrow&quot;,&quot;sans-serif&quot;;color:black&apos;&gt;&lt;/span&gt;&lt;/b&gt;&lt;/p&gt;
        ///  &lt;/td&gt;
        ///  &lt;td valign=top style=&apos;border-top:solid windowtext 1.0pt;
        ///  border-left:solid windowtext 1 [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string Ppusty {
            get {
                return ResourceManager.GetString("Ppusty", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;td valign=top style=&apos;border-top:solid windowtext 1.0pt;
        ///  border-left:solid windowtext 1.0pt;border-bottom:none;border-right:none;
        ///  padding:0cm 0cm 0cm 0cm&apos;&gt;
        ///  &lt;p class=MsoNormal align=center style=&apos;margin-bottom:0cm;margin-bottom:.0001pt;
        ///  text-align:center;line-height:normal;text-autospace:none&apos;&gt;&lt;b&gt;&lt;span
        ///  style=&apos;font-size:9.0pt;font-family:&quot;Arial Narrow&quot;,&quot;sans-serif&quot;;color:black&apos;&gt;&lt;/span&gt;&lt;/b&gt;&lt;/p&gt;
        ///  &lt;/td&gt;
        ///  &lt;td valign=top style=&apos;border-top:solid windowtext 1.0pt;
        ///  border-left:solid windowtext 1 [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string PpustyJednRejBezKW {
            get {
                return ResourceManager.GetString("PpustyJednRejBezKW", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;td valign=top style=&apos;border-top:solid windowtext 1.0pt;
        ///  border-left:solid windowtext 1.0pt;border-bottom:none;border-right:none;
        ///  padding:0cm 0cm 0cm 0cm&apos;&gt;
        ///  &lt;p class=MsoNormal align=center style=&apos;margin-bottom:0cm;margin-bottom:.0001pt;
        ///  text-align:center;line-height:normal;text-autospace:none&apos;&gt;&lt;b&gt;&lt;span
        ///  style=&apos;font-size:9.0pt;font-family:&quot;Arial Narrow&quot;,&quot;sans-serif&quot;;color:black&apos;&gt;&lt;/span&gt;&lt;/b&gt;&lt;/p&gt;
        ///  &lt;/td&gt;
        ///  &lt;td valign=top style=&apos;border-top:solid windowtext 1.0pt;
        ///  border-left:solid windowtext 1 [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string PpustyKW {
            get {
                return ResourceManager.GetString("PpustyKW", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 
        ///  &lt;td valign=top style=&apos;border-top:solid windowtext 1.0pt;
        ///  border-left:solid windowtext 1.0pt;border-bottom:none;border-right:none;
        ///  padding:0cm 0cm 0cm 0cm&apos;&gt;
        ///  &lt;p class=MsoNormal style=&apos;margin-bottom:0cm;margin-bottom:.0001pt;line-height:
        ///  normal;text-autospace:none&apos;&gt;&lt;span style=&apos;font-size:9.0pt;font-family:&quot;Arial Narrow&quot;,&quot;sans-serif&quot;;
        ///  color:black&apos;&gt;&amp;nbsp;&lt;/span&gt;&lt;/p&gt;
        ///  &lt;/td&gt;
        ///  &lt;td valign=top style=&apos;border-top:solid windowtext 1.0pt;
        ///  border-left:solid windowtext 1.0pt;border-bottom:none;bor [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string Puzytek {
            get {
                return ResourceManager.GetString("Puzytek", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 
        ///  &lt;td valign=top style=&apos;border-top:solid windowtext 1.0pt;
        ///  border-left:solid windowtext 1.0pt;border-bottom:none;border-right:none;
        ///  padding:0cm 0cm 0cm 0cm&apos;&gt;
        ///  &lt;p class=MsoNormal style=&apos;margin-bottom:0cm;margin-bottom:.0001pt;line-height:
        ///  normal;text-autospace:none&apos;&gt;&lt;span style=&apos;font-size:9.0pt;font-family:&quot;Arial Narrow&quot;,&quot;sans-serif&quot;;
        ///  color:black&apos;&gt;&amp;nbsp;&lt;/span&gt;&lt;/p&gt;
        ///  &lt;/td&gt;
        ///  &lt;td valign=top style=&apos;border-top:solid windowtext 1.0pt;
        ///  border-left:solid windowtext 1.0pt;border-bottom:none;bor [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string PuzytekJednRejBezKW {
            get {
                return ResourceManager.GetString("PuzytekJednRejBezKW", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 
        ///  &lt;td valign=top style=&apos;border-top:solid windowtext 1.0pt;
        ///  border-left:solid windowtext 1.0pt;border-bottom:none;border-right:none;
        ///  padding:0cm 0cm 0cm 0cm&apos;&gt;
        ///  &lt;p class=MsoNormal style=&apos;margin-bottom:0cm;margin-bottom:.0001pt;line-height:
        ///  normal;text-autospace:none&apos;&gt;&lt;span style=&apos;font-size:9.0pt;font-family:&quot;Arial Narrow&quot;,&quot;sans-serif&quot;;
        ///  color:black&apos;&gt;&amp;nbsp;&lt;/span&gt;&lt;/p&gt;
        ///  &lt;/td&gt;
        ///  &lt;td valign=top style=&apos;border-top:solid windowtext 1.0pt;
        ///  border-left:solid windowtext 1.0pt;border-bottom:none;bor [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string PuzytekKW {
            get {
                return ResourceManager.GetString("PuzytekKW", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;html&gt;
        ///
        ///&lt;head&gt;
        ///&lt;meta http-equiv=Content-Type content=&quot;text/html; charset=windows-1250&quot;&gt;
        ///&lt;meta name=Generator content=&quot;Microsoft Word 12 (filtered)&quot;&gt;
        ///&lt;style&gt;
        ///&lt;!--
        /// /* Font Definitions */
        /// @font-face
        ///	{font-family:&quot;Cambria Math&quot;;
        ///	panose-1:2 4 5 3 5 4 6 3 2 4;}
        ///@font-face
        ///	{font-family:Calibri;
        ///	panose-1:2 15 5 2 2 2 4 3 2 4;}
        ///@font-face
        ///	{font-family:&quot;Arial Narrow&quot;;
        ///	panose-1:2 11 6 6 2 2 2 3 2 4;}
        ///@font-face
        ///	{font-family:&quot;FL Pismo Techniczne&quot;;
        ///	panose-1:0 0 0 0 0 0 0 0 0 0;}
        /// /* Style D [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string SZABLON {
            get {
                return ResourceManager.GetString("SZABLON", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;html&gt;
        ///
        ///&lt;head&gt;
        ///&lt;meta http-equiv=Content-Type content=&quot;text/html; charset=windows-1250&quot;&gt;
        ///&lt;meta name=Generator content=&quot;Microsoft Word 12 (filtered)&quot;&gt;
        ///&lt;style&gt;
        ///&lt;!--
        /// /* Font Definitions */
        /// @font-face
        ///	{font-family:&quot;Cambria Math&quot;;
        ///	panose-1:2 4 5 3 5 4 6 3 2 4;}
        ///@font-face
        ///	{font-family:Calibri;
        ///	panose-1:2 15 5 2 2 2 4 3 2 4;}
        ///@font-face
        ///	{font-family:&quot;Arial Narrow&quot;;
        ///	panose-1:2 11 6 6 2 2 2 3 2 4;}
        ///@font-face
        ///	{font-family:&quot;FL Pismo Techniczne&quot;;
        ///	panose-1:0 0 0 0 0 0 0 0 0 0;}
        /// /* Style D [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string SZABLON_org_ {
            get {
                return ResourceManager.GetString("SZABLON_org_", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;html&gt;
        ///
        ///&lt;head&gt;
        ///&lt;meta http-equiv=Content-Type content=&quot;text/html; charset=utf8&quot;&gt;
        ///&lt;meta name=Generator content=&quot;Microsoft Word 12 (filtered)&quot;&gt;
        ///&lt;style&gt;
        ///&lt;!--
        /// /* Font Definitions */
        /// @font-face
        ///	{font-family:&quot;Cambria Math&quot;;
        ///	panose-1:2 4 5 3 5 4 6 3 2 4;}
        ///@font-face
        ///	{font-family:Calibri;
        ///	panose-1:2 15 5 2 2 2 4 3 2 4;}
        ///@font-face
        ///	{font-family:&quot;Arial Narrow&quot;;
        ///	panose-1:2 11 6 6 2 2 2 3 2 4;}
        ///@font-face
        ///	{font-family:&quot;FL Pismo Techniczne&quot;;
        ///	panose-1:0 0 0 0 0 0 0 0 0 0;}
        /// /* Style Definitio [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string SZABLONJednRejBezKW {
            get {
                return ResourceManager.GetString("SZABLONJednRejBezKW", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;html&gt;
        ///
        ///&lt;head&gt;
        ///&lt;meta http-equiv=Content-Type content=&quot;text/html; charset=windows-1250&quot;&gt;
        ///&lt;meta name=Generator content=&quot;Microsoft Word 12 (filtered)&quot;&gt;
        ///&lt;style&gt;
        ///&lt;!--
        /// /* Font Definitions */
        /// @font-face
        ///	{font-family:&quot;Cambria Math&quot;;
        ///	panose-1:2 4 5 3 5 4 6 3 2 4;}
        ///@font-face
        ///	{font-family:Calibri;
        ///	panose-1:2 15 5 2 2 2 4 3 2 4;}
        ///@font-face
        ///	{font-family:&quot;Arial Narrow&quot;;
        ///	panose-1:2 11 6 6 2 2 2 3 2 4;}
        ///@font-face
        ///	{font-family:&quot;FL Pismo Techniczne&quot;;
        ///	panose-1:0 0 0 0 0 0 0 0 0 0;}
        /// /* Style D [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string SZABLONKW {
            get {
                return ResourceManager.GetString("SZABLONKW", resourceCulture);
            }
        }
    }
}
