//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WZDE.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Miodusy")]
        public string Obreb {
            get {
                return ((string)(this["Obreb"]));
            }
            set {
                this["Obreb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Perlejewo")]
        public string Gmina {
            get {
                return ((string)(this["Gmina"]));
            }
            set {
                this["Gmina"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GK.6642.")]
        public string IdZglPrac {
            get {
                return ((string)(this["IdZglPrac"]));
            }
            set {
                this["IdZglPrac"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MiejsceStarosty {
            get {
                return ((string)(this["MiejsceStarosty"]));
            }
            set {
                this["MiejsceStarosty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string nrDecyzjiStarosty {
            get {
                return ((string)(this["nrDecyzjiStarosty"]));
            }
            set {
                this["nrDecyzjiStarosty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string decyzjaZdnia {
            get {
                return ((string)(this["decyzjaZdnia"]));
            }
            set {
                this["decyzjaZdnia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool radioButtonPoJednostkach {
            get {
                return ((bool)(this["radioButtonPoJednostkach"]));
            }
            set {
                this["radioButtonPoJednostkach"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool radioButtonPoKW {
            get {
                return ((bool)(this["radioButtonPoKW"]));
            }
            set {
                this["radioButtonPoKW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool radioButtonPoJednostkachBezKW {
            get {
                return ((bool)(this["radioButtonPoJednostkachBezKW"]));
            }
            set {
                this["radioButtonPoJednostkachBezKW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool radioButtonPoJednBezKWZUsunieciemNiezmienionychDzialek {
            get {
                return ((bool)(this["radioButtonPoJednBezKWZUsunieciemNiezmienionychDzialek"]));
            }
            set {
                this["radioButtonPoJednBezKWZUsunieciemNiezmienionychDzialek"] = value;
            }
        }
    }
}
